/**
 * COFFEE CHAT - 卡牌数据
 * 共107张卡牌（仅内容，无标题）
 * 咖啡社交主题，深度对话
 */
var CARDS_COFFEE = [
    { id: 1, description: '分享一个你私藏但不希望它排长队的馆子。' },
    { id: 2, description: '如果你去一个陌生的城市，第一站通常会去哪里？' },
    { id: 3, description: '哪种类型的社交会让你觉得「CPU 过载」？' },
    { id: 4, description: '什么样的初次见面瞬间会让你瞬间给对方加分？' },
    { id: 5, description: '如果不上班，你现在最想把时间投入到哪项爱好中？' },
    { id: 6, description: '最近一部让你熬夜也要看完的作品（书/影/剧）是什么？' },
    { id: 7, description: '哪一首歌或者哪段旋律能让你瞬间切换心情？' },
    { id: 8, description: '哪件小事能让你获得即时的、微小的幸福感？' },
    { id: 9, description: '你的「多巴胺来源」最近从什么变成了什么？' },
    { id: 10, description: '你最理想的周末状态，是用哪三个关键词描述的？' },
    { id: 11, description: '你更信奉「延迟满足」还是「及时行乐」？' },
    { id: 12, description: '有什么你坚持了三年以上的小习惯？' },
    { id: 13, description: '你最受不了的生活陋习是什么？' },
    { id: 14, description: '10 年前的你，会怎么看待现在的你？' },
    { id: 15, description: '你学生时代最擅长（或最讨厌）的一门课是什么？' },
    { id: 16, description: '你的第一份实习/工作带给你最深刻的教训是什么？' },
    { id: 17, description: '哪个老师或前辈曾改变过你的人生轨迹？' },
    { id: 18, description: '你小时候梦想的职业，和现在有重合吗？' },
    { id: 19, description: '哪次失败经历，现在回想起来其实是件好事？' },
    { id: 20, description: '如果能给 20 岁的自己写一封信，你只想写哪一句话？' },
    { id: 21, description: '你人生中第一个「高光时刻」发生在什么时候？' },
    { id: 22, description: '哪次搬家的经历让你最有感触？' },
    { id: 23, description: '曾经的哪个梦想，现在的你觉得已经不再重要了？' },
    { id: 24, description: '你所在的行业，外界最大的误解是什么？' },
    { id: 25, description: '在你的领域，什么样的简历会被一眼看中，什么样的会被秒删？' },
    { id: 26, description: '如果我不入行，我永远不会知道的一个内幕是？' },
    { id: 27, description: '这个行业最让你感到幻灭的瞬间是什么？' },
    { id: 28, description: '行业里公认的「顶流公司」，真实的工作体验如何？' },
    { id: 29, description: '为了在这行生存，你学会的最重要的一项软技能是什么？' },
    { id: 30, description: '如果我今天想转行做你的岗位，你最建议我避开哪个坑？' },
    { id: 31, description: '你们行业最迷信（或者最看重）的「成功法则」是什么？' },
    { id: 32, description: '哪种背景的人，在你们领域反而容易出奇制胜？' },
    { id: 33, description: '分享一个你们行业的黑话或缩写，以及它背后的真相。' },
    { id: 34, description: '你的典型工作日，最耗费精力的一件事是什么？' },
    { id: 35, description: '在你的 KPI 里，哪一项最让你觉得无意义却又不得不做？' },
    { id: 36, description: '什么样的同事会让你觉得合作起来极其丝滑？' },
    { id: 37, description: '你的岗位在公司大架构中，到底扮演什么角色？' },
    { id: 38, description: '过去半年，AI 让你的工作流程发生了什么实质性变化？' },
    { id: 39, description: '你最担心 AI 取代你工作中的哪一部分？' },
    { id: 40, description: '有哪些能力是你认为 AI 永远无法模拟的？' },
    { id: 41, description: '你们行业对 AI 的态度是「拥抱」多一点，还是「焦虑」多一点？' },
    { id: 42, description: '哪个 AI 工具是你现在每天必开的？' },
    { id: 43, description: '如果 AI 接管了你 80% 的日常工作，你会把时间花在哪？' },
    { id: 44, description: '你觉得 5 年后，你的这个岗位还会存在吗？' },
    { id: 45, description: '面对技术迭代，你是如何进行「知识更新」的？' },
    { id: 46, description: '分享一个你用 AI 解决的实际工作难题。' },
    { id: 47, description: '你觉得未来的「核心竞争力」会变成什么？' },
    { id: 48, description: '什么时候是你觉得该跳槽或者该转型的信号？' },
    { id: 49, description: '对于刚入行的人，你认为最值得投资的一项能力是什么？' },
    { id: 50, description: '你的职业偶像（Mentor）是谁？你从他身上学到了什么？' },
    { id: 51, description: '在你的领域，学历和工作经验的占比权重是多少？' },
    { id: 52, description: '如何判断一个公司是否真的值得加入，而不是被 HR 忽悠？' },
    { id: 53, description: '如果你现在有 100 万的进修基金，你会怎么花？' },
    { id: 54, description: '最近一个让你感到惊讶的市场信号或消费趋势是什么？' },
    { id: 55, description: '你们行业现在最缺哪种类型的人才？' },
    { id: 56, description: '资本现在对你们这个赛道是什么态度？' },
    { id: 57, description: '分享一个你觉得被低估的商业模式或品牌。' },
    { id: 58, description: '未来的 1-3 年，你觉得你们行业的爆发点在哪？' },
    { id: 59, description: '哪种全球性的变化，正在潜移默化地改变你的生意？' },
    { id: 60, description: '你是如何获取第一手行业信息的？你的信息源有哪些？' },
    { id: 61, description: '你觉得当前的经济环境下，普通人的避风港在哪？' },
    { id: 62, description: '哪个竞争对手的动作让你觉得「这招真绝」？' },
    { id: 63, description: '撕掉现在的名片，你会如何介绍你自己？' },
    { id: 64, description: '如果你的生命是一本书，现在的章节标题叫什么？' },
    { id: 65, description: '你身上哪三个标签是别人给你的，但你并不完全认同？' },
    { id: 66, description: '你最引以为傲的一个「非职业标签」是什么？' },
    { id: 67, description: '分享一个你最近经历的「小型崩溃」时刻。' },
    { id: 68, description: '你生命中最痛苦的一次「清零」是什么？' },
    { id: 69, description: '面对批评或否定，你的第一反应通常是什么？' },
    { id: 70, description: '哪次错误让你支付了最昂贵的学费？' },
    { id: 71, description: '有什么事是你一直想尝试但因为害怕失败而不敢开始的？' },
    { id: 72, description: '你最容易在什么样的事情上产生内耗？' },
    { id: 73, description: '当你感到孤独时，你的「避难所」在哪里？' },
    { id: 74, description: '有没有哪次放弃，让你现在回想起来觉得很庆幸？' },
    { id: 75, description: '你是如何定义「平庸」的？你害怕它吗？' },
    { id: 76, description: '现在的你，追求的是「成功」还是「成就感」？' },
    { id: 77, description: '你觉得赚到多少钱，你才能获得真正的自由？' },
    { id: 78, description: '你的野心，目前在你的优先级别里排第几位？' },
    { id: 79, description: '你最看重的一个人的品质是什么？' },
    { id: 80, description: '什么样的赞美会让你觉得真的被看见了？' },
    { id: 81, description: '如果明天就是世界末日，你最大的遗憾会是什么？' },
    { id: 82, description: '你希望通过工作在世界上留下什么样的印记？' },
    { id: 83, description: '你更想要一份「体面的工作」还是一份「有趣的生活」？' },
    { id: 84, description: '对于「权力和控制感」，你的渴望程度是多少？' },
    { id: 85, description: '分享一个你坚持了很久但被别人说「没用」的事情。' },
    { id: 86, description: '你对财富的原始积累，有什么独特的看法？' },
    { id: 87, description: '哪次消费让你觉得最「物有所值」？' },
    { id: 88, description: '你的物欲，随着年龄的增长是增加了还是减少了？' },
    { id: 89, description: '如果你突然拥有一大笔巨款，你第一件要做的事是什么？' },
    { id: 90, description: '你是如何看待「消费升级」和「极简主义」的？' },
    { id: 91, description: '哪种类型的投资（不限于金融），是你觉得最稳赚不赔的？' },
    { id: 92, description: '金钱在你目前的决策中，权重是多少？' },
    { id: 93, description: '分享一个你对「富足」的定义。' },
    { id: 94, description: '你觉得贫穷带给人最大的伤害是什么？' },
    { id: 95, description: '为了获得财富，你绝对不会逾越的底线是什么？' },
    { id: 96, description: '在你的圈子里，谁是我最应该认识的下一个人？' },
    { id: 97, description: '我能为你提供的、最切实的帮助是什么？' },
    { id: 98, description: '你最近正在推进的、需要外界支持的项目是什么？' },
    { id: 99, description: '我们之间，有没有什么可以「1+1 > 2」的合作契机？' },
    { id: 100, description: '你觉得我身上的哪项资源，对你来说最具吸引力？' },
    { id: 101, description: '分享一个你正在寻找的「合伙人」或「供应商」标准。' },
    { id: 102, description: '除了行业建议，我还能在哪些方面支持你的生活或兴趣？' },
    { id: 103, description: '有没有哪本书或哪个课程，你觉得非常适合现在的我？' },
    { id: 104, description: '我们是否可以建立一个定期的、小范围的深度交流圈？' },
    { id: 105, description: '如果我们要合作一件事，你觉得最理想的开始方式是什么？' },
    { id: 106, description: '下次如果我们再见面，你最想换个什么场景（比如喝酒、看展）？' },
    { id: 107, description: '分享一个你对我今天的整体感觉。' }
];

// 预计算卡牌映射表
var CARD_MAP_COFFEE = {};
for (var i = 0; i < CARDS_COFFEE.length; i++) {
    CARD_MAP_COFFEE[CARDS_COFFEE[i].id] = CARDS_COFFEE[i];
}

module.exports = {
    CARDS_COFFEE: CARDS_COFFEE,
    CARD_MAP_COFFEE: CARD_MAP_COFFEE
};
